runtime: java11
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
handlers:
  - url: /(.*\.html)
    mime_type: text/html
    static_files: static/\1
    upload: static/(.*\.html)
manual_scaling:
  instances: 1